### PR TITLE
cosmoz-bottom-bar-view: added named slot

### PR DESCRIPTION
**Pull request by Wurper**
* Added named slot in cosmoz-bottom-bar-view to reach the extra slot in cosmoz-bottom-bar.
* Added CSS rules for toolbar to apply for extraSlot aswell.
* Issue is RM:19734.

**Wait with merge until OK to do so**

### CODE REVIEW

**Comment by dotpointer** [comment]
@nomego @Wurper What is going on here - can this be merged now? It is very irritating that the buttons in the bottom bar are jumping and this pull request is a step forward to the goal.

It has got two :heavy_check_mark: but the text *Wait with merge until OK to do so* hinders it from getting merged. Is it OK now?

**Comment by nomego** [comment]
Needs approval from @Neovici/uiux

**Comment by sanlifer** [comment]
To clarify - this would move the navigation arrows to the right of the hamburger menu?

If so, then we approve, but we want to try it out in Next first before merging to Alpha. 

@dotpointer @Wurper

**Comment by dotpointer** [comment]
Not sure how to put this on next since this is a component inside `bower_components`. @Wurper do you know how to do it or can someone instruct me how to do it if I should do it? :smile:

**Comment by Wurper** [comment]
@sanlifer This PR in conjunction with https://github.com/Neovici/cosmoz-frontend/pull/636 will move nav buttons right of menu.

@dotpointer in the next branch, open bower.json and replace `"cosmoz-bottom-bar": "neovici/cosmoz-bottom-bar#^2.2.0"` with `"cosmoz-bottom-bar": "neovici/cosmoz-bottom-bar#extraSlot"`

**Comment by dotpointer** [comment]
@sanlifer @Wurper @Neovici/uiux This is now finally testable on Next.

**Comment by dotpointer** [comment]
A problem has arised - this does not work on iOS when @fredrikbernholm tested, the buttons gets stacked on top of each other underneath the browse buttons.

**Comment by nomego** [comment]
How do we move forward with this?

**Comment by dotpointer** [comment]
Assigning this to you @cristinecula since you have the main frontend pull request.

**Comment by fredrikbernholm** [comment]
Tested again in next. The arrows are all gone now, on both desktop and mobile.

**Comment by dotpointer** [comment]
:rotating_light: @megheaiulian (@cristinecula?) - The browse button positions has been reverted - now they are to the left of the actions again. First when I tested they were gone, but they reappeared on the wrong positions after a Ctrl+Shift+R reload.

wrong

Tested this together with the https://github.com/Neovici/cosmoz-frontend/pull/1693 pull request.

Please fix this so it can be reviewed and merged.

**Pull request merged**
