### PR TITLE
Code climate test

### PR DESCRIPTION
**Pull request by megheaiulian**

### CODE REVIEW

**Comment by nomego** [comment]
Do we need that config?
I thought we'd only use it for test coverage ala https://docs.codeclimate.com/docs/travis-ci-javascript-test-coverage ?

**Comment by plequang** [comment]
Looks good, but I don't understand why codeclimate says 2 fixed issues, while the eslint warnings are still there (warning about `mutations` and `kicker` being defined but never used).

**Comment by megheaiulian** [comment]
I think it is some sort of caching? In a commit I pushed the js files were not matching the pattern.
The pull request view on building on codeclimate doesn't show up too much info (all the files that are rated). Once merged I think I can debug it if it's not a caching problem.

**Comment by megheaiulian** [comment]
Not too much info here: https://codeclimate.com/github/Neovici/cosmoz-bottom-bar/builds/21

**Comment by megheaiulian** [comment]
@plequang  The config is wrong but it is fixed now. Still trying to figure out why demo/ isn't included in new rated files

**Pull request merged**
