### PR TITLE
33 - Update to Polymer 2.x - part 2

### PR DESCRIPTION
**Pull request by dotpointer**
Update to Polymer 2.x - part 2.

* Switch to polymer-2 linting ruleset.
* Dropped variants.
* Updated version masks to ^2.0.0.
* Changed to arrow functions.
* Changed var to const and let.

Issue is #33.

### CODE REVIEW

**Comment by dotpointer** [comment]
Not sure how to fix the travis errors, it says `Error: Error thrown outside of test function: Cannot set property 'multi' of undefined` and seems to do with mixins. Have I forgotten something?

**Comment by megheaiulian** [comment]
I think tests should not use timeouts as way to check if something has happened. The timeouts are totally unrelated to the events we're waiting for and it makes tests depend on the execution speed when running.

**Comment by dotpointer** [comment]
> I think tests should not use timeouts as way to check if something has happened. The timeouts are totally unrelated to the events we're waiting for and it makes tests depend on the execution speed when running.

Yes I agree. But how can I wait for the events like scrolling and such to complete without timeouts?

**Comment by dotpointer** [comment]
> @dotpointer In some of tests in this component it's enough to call Polymer.flush() instead of adding a timeout.

Which ones - all with timeouts? There are a lot of tests in this component, I can do it if I know which ones.

**Comment by dotpointer** [comment]
Trying to replace in `cosmoz-bottom-bar-view`.

**Comment by dotpointer** [comment]
All replacements of timeout with flush failed. Now I get a random error:

`Polymer.GestureEventListeners is not a function
    <unknown> at   Polymer.LegacyElementMixin.Polymer.dedupingMixin.base at /components/polymer/lib/legacy/legacy-element-mixin.html:48:0`.

**Comment by dotpointer** [comment]
Seems like it fails again, looked like it was `getEffectiveChildren` that had to be replcaded, but not sure how to replace `<something>`.getEffectiveChildren. Not sure if this is the reason for the current random error, but now it is `Polymer.IronMeta is not a constructor`.

**Comment by dotpointer** [comment]
@megheaiulian Can you have a look please, since you know what you want changed or tell me what to change?

**Comment by megheaiulian** [comment]
@dotpointer I'm currently having a look and will update this PR directly.

**Comment by dotpointer** [comment]
The tests of this pull request now passes, after about 3(!) rebuilds. I started on an error about timeouts, ignored it and rebuilt it. Then I got an error about unexpected token <, I ignored that too and rebuilt again. And now it passes. This is an example of the unstable testing I mentioned in one of the last meetings. With the introduction of Sauce Labs now have tests that not only are harder to debug, they are also failing randomly.

**Comment by dotpointer** [comment]
Windows 10 Chrome beta and dev versions can be omitted from the tests according to nomego, as these seems to be the cause of the errors.

**Comment by megheaiulian** [comment]
@dotpointer I don't think Windows 10 Chrome beta and dev will trigger random errors anymore at least not on this PR. Across components the problem with tests is that they relay on timeouts. As I've done it in this PR we should force synchronous steps in our tests by calling `flush` and `element.flushDebouncer`(or V2 version of that) wherever needed.

**Comment by megheaiulian** [comment]
This can be reviewed and merged! The codeclimate error can be ignored unil the new codeclimate.yml gets on master.

**Pull request merged**
